name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$PRODUCTION_SERVER_SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 159.89.110.201 >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
        env:
          PRODUCTION_SERVER_SSH_KEY: ${{ secrets.PRODUCTION_SERVER_SSH_KEY }}

      - name: Deploy to Production
        run: |
          ssh root@159.89.110.201 "cd /var/www/chat"
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
