name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - run: set -eu
      - run: mkdir "$HOME/.ssh"
      - run: echo "${{ secrets.PRODUCTION_SERVER_SSH_KEY }}" > "$HOME/.ssh/key"
      - run: chmod 600 "$HOME/.ssh/key"

      - name: Deploy to Production
        working-directory: /var/www/chat
        run:
          ssh root@dotstelegrambot.online "cd /var/www/chat && \
            git pull https://github.com/BoMa0103/Chat_livewire_jetstream.git && \
            composer install --no-interaction --prefer-dist --optimize-autoloader && \
            php artisan migrate && \
            npm run build && \
            sudo systemctl reload apache2.service"
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
